#!/usr/bin/env bash
# Display information about subdomains

DOMAIN="$1"
SUBDOMAIN="$2"

if [ $# -eq 2 ]
then
    dig "$SUBDOMAIN.$DOMAIN" | grep -A1 'ANSWER SECTION:' | grep -v 'ANSWER' | awk -v SUBDO="$2" '{print "The subdomain " SUBDO " is a " $4 " record and points to " $5}'
else
    dig "www.$DOMAIN" | grep -A1 'ANSWER SECTION:' | grep -v 'ANSWER' | awk -F' ' '{print "The subdomain www is a " $4 " record and points to " $5}'
    dig "lb-01.$DOMAIN" | grep -A1 'ANSWER SECTION:' | grep -v 'ANSWER' | awk -F' ' '{print "The subdomain lb-01 is a " $4 " record and points to " $5}'
    dig "web-01.$DOMAIN" | grep -A1 'ANSWER SECTION:' | grep -v 'ANSWER' | awk -F' ' '{print "The subdomain web-01 is a " $4 " record and points to " $5}'
    dig "web-02.$DOMAIN" | grep -A1 'ANSWER SECTION:' | grep -v 'ANSWER' | awk -F' ' '{print "The subdomain web-02 is a " $4 " record and points to " $5}'
fi
