#!/usr/bin/env bash
# Transfer a file from our client to a server
if [ $# -lt 3 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp -o StrictHostKeyChecking=no -i "$1" "$2" "$3" "$4"
fi
