#!/usr/bin/env bash
# Install nginx web server
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo chmod 666 /var/www/html/index.nginx-debian.html
echo "Holberton School for the win!" > /var/www/html/index.nginx-debian.html
sudo service nginx restart
