#!/usr/bin/env bash
# Use the until loop
phrase="Holberton School"
i=0
while ((i<10)); do
    if [ "$i" -eq 3 ]
    then
        echo "bad luck"
    elif [ "$i" -eq 7 ]
    then
        echo "good luck"
    else
    echo "$phrase"
    fi
    i=$((i + 1))
done
