#!/usr/bin/env bash
# Show the hours and minutes
hour=0
minute=1
while ((hour<=12)); do
    echo "Hour: $hour"
    hour=$((hour + 1))
    while ((minute<=59))
    do
        echo "$minute"
        minute=$((minute + 1))
    done
    minute=1
done
