#!/bin/bash
# Configure ufw so that it blocks all incoming traffic, except the following TCP ports: 22, 443, 80
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw enable
sudo ufw reload
