#!/usr/bin/env bash
# Nginx must be running as nginx user

sudo sed -i 's/listen 80 default_server;/ listen 8080 default_server;/' /etc/nginx/sites-enabled/default
sudo sed -i 's/listen \[::\]:80 default_server/ listen [::]:8080 default_server/' /etc/nginx/sites-enabled/default
sudo sed -i 's/#user www-data;/user nginx;/' /etc/nginx/nginx.conf
sudo chmod 777 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx restart
