#!/usr/bin/env bash
# Nginx must be running as nginx user in 7 lines or less
sudo sed -i 's/80/8080/' /etc/nginx/sites-enabled/default
sudo sed -i 's/#user www-data/user nginx/' /etc/nginx/nginx.conf
sudo chmod 777 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx restart
